Public with sharing Class AppleWatch{
 Public Static void appleWatchmethod(list<Opportunity> lopt ){
    for (Opportunity opp : lopt) {
        Task t        = new Task();
        t.Subject     = 'Apple Watch Promo' ;
        t.Description = 'Send them one ASAP' ;
        t.Priority    = 'High' ;
        t.WhatId      = opp.Id;
     // t.Activity_Custom_field_2__c     = true;
        insert t;
     /*Comment Dev1 Org FINAL*/
     /*Comment 2*/
   }
  }
 }